# Generated by Django 4.2.30 on 2026-04-08 19:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AudioSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Untitled Session', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sample_rate', models.IntegerField(default=44100)),
                ('duration', models.FloatField(blank=True, null=True)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='audio/')),
                ('status', models.CharField(choices=[('recording', 'Recording'), ('uploaded', 'Uploaded'), ('analyzing', 'Analyzing'), ('completed', 'Completed'), ('error', 'Error')], default='uploaded', max_length=20)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NoteSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.FloatField()),
                ('end_time', models.FloatField()),
                ('duration', models.FloatField()),
                ('frequency', models.FloatField()),
                ('note_name', models.CharField(max_length=10)),
                ('midi_note', models.FloatField()),
                ('cents', models.FloatField()),
                ('confidence', models.FloatField()),
                ('pitch_drift', models.FloatField(default=0.0)),
                ('has_vibrato', models.BooleanField(default=False)),
                ('velocity_estimate', models.FloatField(default=0.5)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_segments', to='audio.audiosession')),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='ChordEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.FloatField()),
                ('duration', models.FloatField()),
                ('chord_symbol', models.CharField(max_length=20)),
                ('root', models.CharField(max_length=5)),
                ('quality', models.CharField(max_length=20)),
                ('confidence', models.FloatField()),
                ('roman_numeral', models.CharField(blank=True, default='', max_length=10)),
                ('harmonic_function', models.CharField(blank=True, default='', max_length=20)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chord_events', to='audio.audiosession')),
            ],
            options={
                'ordering': ['time'],
            },
        ),
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(blank=True, max_length=20)),
                ('key_confidence', models.FloatField(default=0.0)),
                ('scale', models.CharField(blank=True, max_length=50)),
                ('tempo_bpm', models.FloatField(blank=True, null=True)),
                ('num_notes', models.IntegerField(default=0)),
                ('num_phrases', models.IntegerField(default=0)),
                ('analysis_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='audio.audiosession')),
            ],
        ),
        migrations.CreateModel(
            name='PitchData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.FloatField()),
                ('frequency', models.FloatField()),
                ('confidence', models.FloatField()),
                ('midi_note', models.FloatField()),
                ('note_name', models.CharField(max_length=10)),
                ('cents', models.FloatField()),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pitch_data', to='audio.audiosession')),
            ],
            options={
                'ordering': ['time'],
                'indexes': [models.Index(fields=['session', 'time'], name='audio_pitch_session_c17d7d_idx')],
            },
        ),
    ]
