# Generated by Django 4.2.30 on 2026-04-08 19:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('audio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TheoryAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=20)),
                ('mode', models.CharField(default='major', max_length=20)),
                ('cadences', models.JSONField(blank=True, default=list)),
                ('matched_progressions', models.JSONField(blank=True, default=list)),
                ('harmonic_distribution', models.JSONField(blank=True, default=dict)),
                ('full_analysis', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='theory_analyses', to='audio.audiosession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
