# Generated by Django 4.2.30 on 2026-04-08 19:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MidiFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Untitled MIDI', max_length=255)),
                ('file', models.FileField(upload_to='midi/')),
                ('num_tracks', models.IntegerField(default=0)),
                ('duration', models.FloatField(blank=True, null=True)),
                ('tempo_bpm', models.FloatField(blank=True, null=True)),
                ('time_signature', models.CharField(blank=True, default='4/4', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('analyzing', 'Analyzing'), ('completed', 'Completed'), ('error', 'Error')], default='uploaded', max_length=20)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MidiNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track', models.IntegerField(default=0)),
                ('channel', models.IntegerField(default=0)),
                ('pitch', models.IntegerField()),
                ('velocity', models.IntegerField()),
                ('start_time', models.FloatField()),
                ('end_time', models.FloatField()),
                ('duration', models.FloatField()),
                ('note_name', models.CharField(max_length=10)),
                ('midi_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='midi_analysis.midifile')),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='MidiAnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(blank=True, max_length=20)),
                ('key_confidence', models.FloatField(default=0.0)),
                ('chord_progression', models.JSONField(default=list)),
                ('roman_numerals', models.JSONField(default=list)),
                ('harmonic_functions', models.JSONField(default=list)),
                ('voice_leading', models.JSONField(default=list)),
                ('analysis_source', models.CharField(choices=[('r', 'R Language'), ('python', 'Python')], default='python', max_length=10)),
                ('full_analysis', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('midi_file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='midi_analysis.midifile')),
            ],
        ),
    ]
